### ISSUE TITLE
Research Supabase

### ISSUE THREAD

**Issue by IrakliAmbroladze** [IrakliAmbroladze/tbc_x_usaid#1]
ამ თასქის ქვეშ დავწეროთ supabase-თან დაკავშირებული ზოგადი საკითხები

**Comment by IrakliAmbroladze** [comment]
@elenetskitishvili რა წყაროებს იყენებ?

**Comment by elenetskitishvili** [comment]
ვიყენებ შემდეგ წყაროებს: supabase-ის დოკუმენტაცია, udemy-ის და youtube-ის ტუტორიალები, google. ქვემოთ გაგიზიარებ ჩემს მიერ მოძიებულ ინფორმაციას სუპაბეისთან დაკავშირებით:

- სუპაბეისი არის სერვისი, რითიც ვქმნით ბექენდს Postgres დატაბაზით. სუპაბეისი ავტომატურად ქმნის დატაბაზას და matching API-ს რომელსაც მერე ჩვენ გავუკეთებთ დატას რექვესთს  და წამოვიღებთ დატას სერვერიდან.
- Database პასვორდისთვის უმჯობესი იქნება ჩასაწერი ველის ქვეშ არსებული **Generate a password**-ით დააგენერირო ვიდრე შენ თვითონ მოიგონო. დაგენერირებული პასვორდი სადმე შეინახე.
-  **Table Editor**-ში დაგვჭირდება ორი table-ის შექმნა: ერთი პროდუქტებისთვის, მეორე ბლოგპოსტებისათვის.
-  სუპაბეისი ავტომატურად ქმნის მთლიან **API დოკუმენტაციას** ყველა ჩვენი table-ებისთვის.
- Table-ის შექმნისას მონიშნული უნდა იყოს **Row Level Security (RLS)**-ის გრაფა, რომელიც უზრუნველყოფს, იუზერებს წვდომა და ცვლილებების განხორციელების შესაძლებლობა ჰქონდეთ მხოლოდ მათ დატაზე, რაც უმნიშვნელოვანესია security-ის თვალსაზრისით.
- **Row Level Security (RLS) policies** გვჭირდება რომ ვაკონტროლოთ წვდომა  database-თან. მისი შექმნა შეგვიძლია Authentication --> Policies-ში.
- Buckets  Supabase-ში გამოიყენება ისეთი ფაილების შესანახად, როგორიცაა სურათები, ვიდეოები... ჩვენ გამოვიყენებთ პროდუქტების ფოტოების შესანახად.

**Comment by IrakliAmbroladze** [comment]
რამე კონკრეტული ლინკიც თუ გაქვს, ეგეც ჩააგდე

**Comment by elenetskitishvili** [comment]
1. https://supabase.com/docs/guides/getting-started/quickstarts/nextjs

(პერიოდულად დავააფდეითებ და ახალ ლინკებს დავამატებ)

**Comment by IrakliAmbroladze** [comment]
Row Level Security 
https://supabase.com/docs/guides/database/postgres/row-level-security

**Comment by IrakliAmbroladze** [comment]
რეაქტზეა, მაგრამ გამოგვადგება. Connecting to Supabase
https://www.youtube.com/watch?v=Gz9bvYybaws&list=PL4cUxeGkcC9hUb6sHthUEwG7r9VDPBMKO&index=3

**Comment by IrakliAmbroladze** [comment]
ესეც იგივე ტიპია, use client არის, მაგრამ სერვერულად ადვილად გადავაწყობთ
https://www.youtube.com/watch?v=VjohMDwjty4&list=PL4cUxeGkcC9hUb6sHthUEwG7r9VDPBMKO&index=4
უშუალოდ კოდში ინფორმაციის წამოღებაზეა. იდეაში ისაა, რაც api-ში უნდა გაკეთდეს

**Comment by elenetskitishvili** [comment]
ირაკლი, პროდუქტების კონტენტთან დაკავშირებით რა გადაწყვიტე? რეალური პროდუქციის დატას მომაწოდებ?

**Comment by IrakliAmbroladze** [comment]
რა ინფორმაცია დაგჭირდება მითხარი და მოგაწვდი, თუ მაქვს. მე შემიძლია მოგაწოდო სურათი, დასახელება და აღწერა. კიდე რამე დაგჭირდება?

**Comment by elenetskitishvili** [comment]
- `npm i @supabase/supabase-js`  ჩავწერთ ტერმინალში;
- .env.local-ში უნდა ჩავწეროთ:

1.  **SUPABASE_URL** (რომელიც მდებარეობს აქ: Project Settings --> API --> API Settings --> ProjectURL)  
2. **SUPABASE_KEY** (რომელიც მდებარეობს აქ: Project Settings --> API --> API Settings-->Project API Keys -->service_role

- ჩვენი **supabase.js** უნდა გამოიყურებოდეს ასე: 
```
import { createClient } from "@supabase/supabase-js";

export const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_KEY
);
```

**Comment by elenetskitishvili** [comment]
ირაკლი, ორი შემოთავაზება მაქვს შენთან: 

1. სუპაბეისთან დაკავშირებული კომიტი გავაკეთოთ როგორც co-authored commit
2.  შევქმნათ ერთი ბრენჩი, რომელსაც სავარაუდოდ ერქმევა feature/supabase-setup.  ჩვენი სამუშაო ბრენჩი მე შევქმნა თუ შენ შექმნი  ?

**Comment by IrakliAmbroladze** [comment]
მშვენიერი სახელია, შექმენი, ოღონდ develop ბრენჩიდან. co-authored commit ეს ამიხსენი უფრო ზისტად

**Comment by elenetskitishvili** [comment]
co-authored commit კეთდება, როდესაც ორი ადამიანი მუშაობს ერთსა და იმავე კომიტზე. ერთ-ერთი ჩვენგანი დააკომიტებს და მეორე ჩვენგანს მონიშნავს, როგორც კომიტის თანაავტორს. 
co-authored commit-ის გაკეთება ყველაზე ადვილი github desktop-ის გამოყენებითაა, თუმცა როგორც ვიცი ტერმინალიდანაცაა შესაძლებელი, თუმცა მე ტერმინალიდან არ მიცდია. 
გითჰაბ დესკტოპს კომიტის მესიჯის ჩასაწერ ფილდთან აქვს თანაავტორების დასამატებელი ღილაკი.

**Comment by IrakliAmbroladze** [comment]
საჭიროება რატომ არის რომ ორივემ ერთ კომიტზე ვიმუშაოთ?

**Comment by elenetskitishvili** [comment]
მუშაობას რომ დავიწყებთ პროცესში უფრო ცხადად გამოჩნდება საერთო კომიტის აუცილებლობა.

**Comment by IrakliAmbroladze** [comment]
კარგი, მინდა დამარწმუნო : ))

**Comment by elenetskitishvili** [comment]
Organization Settings --> Team აქ უნდა დამამატო member-ად, რომ შევძლო შენს პროექტზე მუშაობა.

**Comment by IrakliAmbroladze** [comment]
ვცადოთ ახლავე. შენი User დამჭირდება ალბათ
