### ISSUE TITLE
TypeScript-ზე გადაწყობა

### ISSUE THREAD

**Issue by IrakliAmbroladze** [IrakliAmbroladze/tbc_x_usaid#12]
პროექტი სრულად გადასაწყობია ტაიპსკრიპტზე

**Comment by Nikoloz01** [comment]
გავაკეთე შემდეგი რაღაცეები

**TypeScript-ის დამატება**
   - TypeScript-ის ინსტალაცია და საწყისი კონფიგურაციის ჩამოყალიბება.
   - `tsconfig.json` ფაილის რედაქტირება და პროექტის დეფენდენსების განახლება.

**.jsx` ფაილები გადავარქვი `.tsx` ფორმატში TypeScript-ის სრულ მხარდაჭერისთვის**

**type error ების მოგვარება**

**კომპონენტების რეფაქტორინგი და TypeScript ტიპების დამატება tsx ფაილებში**
---

**Comment by Nikoloz01** [comment]
ბოლო კომიტებში js ფაილები გადავაწყვე typescript ზე, ძირითადად fetch და route ფაილები, რადგან ისინი ამუშავებენ  ლოგიკას, როგორიცაა API მოთხოვნები და სერვერის მხრიდან პასუხები. გვაქვს  input და output ები სადაც ვიყენებთ TypeScript ს value ების ტიპების განსასაზღვრად.

უცვლელი დავტოვე ზოგიერთი js ფაილი [language.js, ThemeToggle.js] რადგან ისინი ძირითადად ამუშავებენ ინტერფეისის მარტივ ინტერაქციას, ამ კომპონენტებს არ აქვთ რთული ლოგიკა და არ საჭიროებენ ტიპების განსაზღვრას

**Comment by IrakliAmbroladze** [comment]
მშვენიერი ნიკა. ფულ რიქვესთი დაგვჭირდება. თუმცა ჯერ fetchProducts.js da fetchPosts.js -კონფლიქტი რომ არ იყოს მაგას გადავამოწმებთ მე ლუკა და დემეტრე
