### ISSUE TITLE
Research API

### ISSUE THREAD

**Issue by IrakliAmbroladze** [IrakliAmbroladze/tbc_x_usaid#5]
აქ ჩავაგდოთ api-s საკითხები

**Comment by lukaabramishvili** [comment]
API endpoints serve as the specific digital locations where client requests for information are sent by one program to retrieve the digital resource that exists there. They're the points at which the client and the server communicate, enabling two applications to share resources.

**Comment by IrakliAmbroladze** [comment]
კი. ჩვენს შემთხვევაში გამოვა ისე, რომ კლიენტი მიაკითხავს api-ს და არა სუპაბეიზს
