### ISSUE TITLE
feature/post-API

### ISSUE THREAD

**Issue by IrakliAmbroladze** [IrakliAmbroladze/tbc_x_usaid#6]
ლუკა ეს არის შენი ბრენჩი პოსტების API-თვის

**Comment by IrakliAmbroladze** [comment]
api ფოლდერში დაგვჭირდება posts ფოლდერში route.js-ის შემქნა
ამ კოდს ინფორმაცია მოაქვს ბაზიდან
import { createClient } from '@supabase/supabase-js'
const supabaseUrl = 'https://cbhoxdzzhvcuajscuqes.supabase.co'
const supabaseKey = process.env.SUPABASE_KEY
const supabase = createClient(supabaseUrl, supabaseKey)

export const GET = async (req, res) => {
   let { data: posts, error } = await supabase
  .from('posts')
  .select('title')
return Response.json(posts)
}

**Comment by lukaabramishvili** [comment]
გასაგებია ირაკლი ვცადე ეგ ვარიანტი და ახლა ერორის მოგვარების პროცესში ვარ.

**Comment by IrakliAmbroladze** [comment]
მთავარი ნაწილი შესრულებულია, შეიძ₾ება მცირე ჩარევა დასჭირდეს
